const notes = [
  {title:'API Foundations and HTTP Pitfalls',topic:'qa',label:'API TESTING',depth:'MUST KNOW',summary:'Client/server architecture and a two-part guide review: HTTP misconceptions, data formats and a practical contract checklist.',file:'../../qa/api-testing/api-foundations-and-http-pitfalls.md'},
  {title:'MCP and the Host Tool Loop',topic:'ai',label:'AI AGENTS',depth:'SHOULD KNOW',summary:'Understand model proposals, host execution and MCP integration, with protocol corrections and a personal-assistant exercise.',file:'../../ai/agents/mcp-host-tool-loop.md'},
  {title:'Automating Release Coordination',topic:'qa',label:'QA PROCESS',depth:'SHOULD KNOW',summary:'An Ozon mobile-release case study: automate preparation, ownership and telemetry while preserving release decisions.',file:'../../qa/qa-process/release-orchestration.md'},
  {title:'Composing UI Test Components',topic:'qa',label:'AUTOMATION',depth:'SHOULD KNOW',summary:'Apply component composition to repeated UI elements. Review the tradeoffs of Atomic Design and Page Objects.',file:'../../qa/automation/atomic-test-composition.md'},
  {title:'Machine Learning Foundations for QA',topic:'ai',label:'AI TESTING',depth:'SHOULD KNOW',summary:'Understand precision, recall, thresholds and data leakage through a defect-triage example. Four ML Glossary chapters reviewed with corrections.',file:'../../ai/llm-testing/ml-foundations-for-qa.md',details:['Confusion matrix and worked metric calculations','Training, validation and test workflow','Source review with explicit coverage and corrections']},
  {title:'REST API Request Basics',topic:'qa',label:'API TESTING',depth:'MUST KNOW',summary:'Read an API exchange as request plus response. Check contract, data, permissions, and side effects together.',file:'../../qa/api-testing/rest-api-request-basics.md',details:['URL anatomy, HTTP methods, headers, status codes, and valid JSON','Editable request-flow diagram and practical GET scenario','Corrections for contract-dependent query parameters and PUT/PATCH semantics']},
  {title:'Testing Concepts',topic:'qa',label:'FUNDAMENTALS',depth:'MUST KNOW',summary:'Separate test levels, quality attributes, change-related purposes, and execution approaches.',file:'../../qa/fundamentals/testing-concepts.md',details:['Component, integration, system, and acceptance boundaries','Functional, non-functional, regression, and smoke testing','Defect lifecycle diagram and risk-based coverage']},
  {title:'Exploratory Testing Heuristics',topic:'qa',label:'MANUAL TESTING',depth:'MUST KNOW',summary:'A compact question generator for interruptions, boundaries, relationships, concurrency, and input routes.',file:'../../qa/manual-testing/exploratory-heuristics.md',details:['Ten practical exploration lenses','Timeboxed session example','Heuristics guide questions; they do not prove complete coverage']},
  {title:'Form Testing',topic:'playbook',label:'CHECKLIST',depth:'MUST KNOW',summary:'A field-by-field matrix for valid, invalid, boundary, security, submission, and persistence checks.',file:'../../playbooks/checklists/form-testing.md',details:['Presence, length, numeric, date, text, and structured input','Server-side validation and feedback checks','Security probes framed as evidence-based tests']},
  {title:'Web UI Testing',topic:'qa',label:'WEB TESTING',depth:'MUST KNOW',summary:'Test components, states, keyboard behavior, responsive layout, accessibility, and pagination.',file:'../../playbooks/checklists/web-ui-testing.md',details:['Buttons, modals, tables, date pickers, carousels, and breadcrumbs','Mobile, keyboard, screen-reader, and locale checks','Design choices separated from universal requirements']},
  {title:'Risk-Based Test Planning',topic:'qa',label:'QA PROCESS',depth:'SHOULD KNOW',summary:'Connect product risks to scope, evidence, people, environments, and a release decision.',file:'../../qa/qa-process/test-planning.md',details:['Planning workflow diagram','Entry, suspension, resumption, and exit criteria','Explicit QA, developer, platform, and product ownership']},
  {title:'OpenAI Academy for QA',topic:'ai',label:'AI FOR QA',depth:'SHOULD KNOW',summary:'A practical resource for turning AI assistance into repeatable, reviewable QA workflows.',file:'../../ai/ai-for-testing/openai-academy-workplace-ai.md',details:['AI Foundations, Applied AI Foundations, and Agents and Workflows','Proposed QA exercises with evidence to review','Vendor announcement separated from independent validation']},
  {title:'Test Plan Template',topic:'playbook',label:'TEMPLATE',depth:'MUST KNOW',summary:'A reusable planning canvas for scope, risks, approach, responsibilities, criteria, and release discussion.',file:'../../playbooks/templates/test-plan.md',details:['Risk and evidence table','Environment and dependency prompts','Results, residual risk, and decision record']}
];
const cards=document.querySelector('#cards'), search=document.querySelector('#search'), filter=document.querySelector('#filter'), dialog=document.querySelector('#note-dialog'), dialogContent=document.querySelector('#dialog-content');
function render(){const term=search.value.toLowerCase(), kind=filter.value; const visible=notes.filter(n=>(kind==='all'||n.topic===kind)&&(`${n.title} ${n.summary} ${n.label}`.toLowerCase().includes(term)));document.querySelector('#total-count').textContent=visible.length;cards.innerHTML=visible.map((n,i)=>`<article class="card" data-index="${notes.indexOf(n)}"><div class="card-top"><span class="pill ${n.topic}">${n.label}</span><span class="depth">${n.depth}</span></div><h3>${n.title}</h3><p>${n.summary}</p><div class="card-foot"><span>Read note</span><span class="arrow">↗</span></div></article>`).join('')||'<p>No notes match this search yet.</p>';cards.querySelectorAll('.card').forEach(c=>c.addEventListener('click',()=>openNote(notes[c.dataset.index])))}
function openNote(n){const url=new URL('./reader.html',location.href);url.searchParams.set('note',n.file.replace(/^\.\.\/\.\.\//,''));location.href=url.href}
search.addEventListener('input',render);filter.addEventListener('change',render);document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
