import {icon,visual,toolBadge} from './icons.js';
const {lang}=window.labI18n;
const L=(ru,en)=>lang==='ru'?ru:en;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups={
 foundations:[L('Основы и тест-дизайн','Foundations & test design'),L('Понятия, требования, исследование и практические проверки.','Concepts, requirements, exploration and practical checks.'),'◈','#668477','#eaf3ee'],
 delivery:[L('Релизы и процессы','Releases & processes'),L('От планирования и onboarding до решения о выпуске.','From planning and onboarding to release decisions.'),'↗','#b17d47','#fbf1e4'],
 automation:[L('Автоматизация','Automation'),L('Архитектура тестов, Python, CI/CD и инженерные практики.','Test architecture, Python, CI/CD and engineering practices.'),'⌘','#6661ba','#eeecfa'],
 interfaces:[L('API и безопасность','API & security'),L('Контракты, доступ, HTTP и интеграции.','Contracts, access, HTTP and integrations.'),'⇄','#477f98','#e7f2f7'],
 experience:[L('Web, Mobile и скорость','Web, mobile & performance'),L('Интерфейсы, устройства, нагрузка и пользовательский опыт.','Interfaces, devices, load and user experience.'),'▦','#ae6578','#f9edf1'],
 ai:[L('AI и агенты','AI & agents'),L('Основы AI, проверяемые агенты и применение в работе.','AI foundations, verifiable agents and everyday applications.'),'✳','#8364b0','#f1ebf8']};
const tools=[
 ['Handy','https://handy.computer/',L('Голос → текст','Voice → text'),L('Локальная диктовка в активное поле. Удобно для заметок и AI-промптов. Проверьте текст перед отправкой; облачная постобработка включается отдельно.','Local dictation into the active field for notes and AI prompts. Review before sending; cloud post-processing is optional.'),['ai','delivery'],'handy-local-speech-to-text'],
 ['Bundlephobia','https://bundlephobia.com/',L('Размер npm-пакетов','npm package size'),L('Предварительная оценка размера зависимости. Сравнивайте точные версии, затем измеряйте реальную production-сборку.','Estimate dependency size. Compare exact versions, then measure the actual production build.'),['automation','experience'],'bundlephobia-npm-cost-check'],
 ['delphitools','https://delphi.tools/',L('Файлы и изображения','Files & images'),L('Конвертация изображений, PDF и документов, палитры и контраст. Сохраняйте оригинал и проверяйте качество экспорта.','Image, PDF and document utilities, palettes and contrast checks. Keep originals and inspect exports.'),['experience','foundations'],'delphitools-file-utilities'],
 ['AIToolTree','https://aitooltree.com/',L('Каталог AI','AI directory'),L('Поиск AI-сервисов. Условия, возможности и цену выбранного инструмента проверяйте у поставщика.','Discover AI services. Verify capabilities, pricing and terms with the vendor.'),['ai'],'aitooltree-discovery-guide'],
 ['NotebookLM','https://notebooklm.google.com/',L('Работа с источниками','Source-based research'),L('Вопросы и заметки по загруженным источникам. Проверяйте цитаты и качество исходных транскриптов.','Questions and notes grounded in uploaded sources. Check citations and transcript accuracy.'),['ai','delivery'],'qa-meeting-transcription-toolkit'],
 ['Google AI Studio','https://aistudio.google.com/',L('AI-эксперименты','AI experiments'),L('Промпты и анализ аудио с Gemini. Используйте разрешённые данные и проверяйте полученные выводы.','Prompt experiments and audio analysis with Gemini. Use approved data and verify conclusions.'),['ai'],'qa-meeting-transcription-toolkit'],
 ['HypeScribe','https://www.hypescribe.com/ru',L('Встречи и транскрипты','Meetings & transcripts'),L('Транскрипция и саммари встреч. Проверьте лимиты тарифа и настройки хранения записей.','Meeting transcription and summaries. Check plan limits and recording retention.'),['ai','delivery'],'qa-meeting-transcription-toolkit'],
 ['MacWhisper','https://www.macwhisper.net/',L('Транскрипция на Mac','Transcription on Mac'),L('Расшифровка аудиофайлов. Выбирайте режим обработки и модель под язык и компьютер.','Audio-file transcription. Choose the processing mode and model for your language and hardware.'),['ai'],'qa-meeting-transcription-toolkit'],
 ['Format Factory','https://www.softportal.com/software-9536-format-factory.html',L('Конвертация медиа','Media conversion'),L('Подготовка аудио и видео на Windows перед транскрипцией. Проверяйте источник установщика и параметры экспорта.','Prepare audio and video on Windows before transcription. Check installer provenance and export settings.'),['ai'],'qa-meeting-transcription-toolkit']
];
const views={overview:[L('Обзор','Overview'),'◈',L('Знания, которые связаны.','Knowledge, connected.'),L('Выберите направление. Статьи, AI-практики, инструменты и оригиналы собраны вокруг одной задачи.','Choose a direction. Articles, AI practices, tools and originals are connected around the work.')],library:[L('Библиотека','Library'),'▤',L('Библиотека знаний','Knowledge library'),L('Все статьи и практические руководства. Найдите тему или выберите направление.','All articles and practical guides. Search a topic or choose a domain.')],tools:[L('Инструменты','Tools'),'⌘',L('Небольшие инструменты. Большая польза.','Small tools. Useful shortcuts.'),L('Выберите инструмент: краткое описание, рекомендация и прямая ссылка.','Pick a tool for a short description, a useful tip and a direct link.')],materials:[L('Материалы','Materials'),'▧',L('Оригиналы под рукой','Originals at hand'),L('Загруженные PDF, шпаргалки и методички. Версии сохранены отдельно.','Uploaded PDFs, cheat sheets and guides. Versions are kept separately.')],sources:[L('Источники','Sources'),'↗',L('Откуда берутся знания','Where knowledge comes from'),L('Ссылки без повторов. Под каждым источником — материалы, в которых он используется.','Deduplicated links. Each source leads back to the notes that use it.')]};
let data; const content=document.querySelector('#content');
const params=()=>new URLSearchParams(location.search);
function route(v,extra={}){const p=new URLSearchParams({view:v,lang,...extra});return './index.html?'+p}
function reader(n){return './reader.html?'+new URLSearchParams({note:n.path,lang,from:location.pathname+location.search})}
const title=n=>n.title[lang]||n.title.en;
const card=n=>`<a class="card" style="${visual(n).style}" href="${esc(reader(n))}"><span class="visual-icon article-icon">${icon(visual(n).shape)}</span><span class="meta">${esc(n.domain.toUpperCase()+' / '+groups[n.group][0])}</span><h3>${esc(title(n))}</h3><span class="card-end">${L('Читать материал','Read article')} ↗</span></a>`;
const chips=items=>`<div class="tool-grid">${items.map(t=>`<button class="tool-chip" data-tool="${esc(t[0])}">${toolBadge(t[0])}<span><strong>${esc(t[0])}</strong><small>${esc(t[2])}</small></span></button>`).join('')}</div>`;
const heading=(s,link='')=>`<div class="section-heading"><h2>${esc(s)}</h2>${link}</div>`;
function materialGroup(m){return /TDD/i.test(m.name)?'automation':/методолог|onboarding|release/i.test(m.name)?'delivery':'foundations'}
function materialName(m){return m.name.replace(/^2026-09-21-/,'').replace('testing-foundations-blocks-1-3',L('Основы тестирования · Блоки 1–3','Testing foundations · Blocks 1–3')).replace('testing-foundations-block-1-new',L('Основы тестирования · Блок 1 · New','Testing foundations · Block 1 · New')).replace('qa-release-playbook','QA Release Playbook').replaceAll('_',' ')}
function materialRow(m){const id=/TDD/i.test(m.name)?'agile-devops-tdd-quality-strategies':/методолог/i.test(m.name)?'software-development-methodologies':/onboarding/i.test(m.name)?'qa-onboarding-checklist-review':/release/i.test(m.name)?'release-readiness-playbook':'testing-foundations-blocks-1-3-review';const linked=data.notes.filter(n=>n.id===id);return `<div class="resource"><a href="${esc('../../'+m.path)}" target="_blank" rel="noopener">▧ ${esc(materialName(m))} ↗</a><small>PDF · ${(m.bytes/1024/1024).toFixed(1)} MB</small><div class="related-links">${linked.map(n=>`<a href="${esc(reader(n))}">${esc(title(n))} →</a>`).join('')}</div></div>`}
const relatedAI={
 foundations:['ai-assisted-acceptance-criteria','ai-assisted-qa-documentation'],
 delivery:['evidence-led-test-triage','ai-assisted-acceptance-criteria'],
 automation:['evidence-engineered-qa-agent','production-coding-agent-controls','specialized-workflow-evaluation'],
 interfaces:['mcp-for-qa','permission-aware-analytics'],
 experience:['evidence-engineered-qa-agent','evidence-led-test-triage']
};
function render(){
 const p=params();let view=p.get('view')||'overview';if(!views[view]&&view!=='topic')view='overview';const g=p.get('group');if(view==='topic'&&!groups[g])view='overview';const active=view==='topic'?'overview':view;const v=views[active];const q=p.get('q')||'';const domain=p.get('domain')||'all';
 document.querySelector('#navigation').innerHTML=Object.entries(views).map(([id,x])=>`<a class="nav-link ${id===active?'active':''}" ${id===active?'aria-current="page"':''} href="${route(id)}"><span class="nav-icon" aria-hidden="true">${icon({overview:"grid",library:"book",tools:"package",materials:"files",sources:"link"}[id])}</span>${x[0]}</a>`).join('');
 document.querySelector('#breadcrumb').textContent=L('Пространство / ','Workspace / ')+(view==='topic'?groups[g][0]:v[0]);document.querySelector('#eyebrow').textContent=view==='topic'?L('СВЯЗАННЫЕ ТЕМЫ','CONNECTED TOPICS'):'QA AI LAB / '+v[0].toUpperCase();document.querySelector('#page-title').textContent=view==='topic'?groups[g][0]:v[2];document.querySelector('#page-description').textContent=view==='topic'?groups[g][1]:v[3];document.title=(view==='topic'?groups[g][0]:v[0])+' · QA AI Lab';document.querySelector('#rail-note').textContent=L('Ваше рабочее пространство для QA, AI и полезных инструментов.','Your workspace for QA, AI and useful tools.');
 const ctrl=document.querySelector('#controls');ctrl.innerHTML=view==='overview'||view==='topic'?'':`<div class="toolbar"><input type="search" id="search" aria-label="${L('Поиск','Search')}" placeholder="${L('Найти…','Search…')}" value="${esc(q)}">${view==='library'?`<div class="filters">${['all','qa','ai'].map(d=>`<a class="${domain===d?'selected':''}" href="${route(view,{domain:d,q})}">${d==='all'?L('Все темы','All topics'):d.toUpperCase()}</a>`).join('')}</div><select id="sort" aria-label="${L('Сортировка','Sort')}"><option value="recent">${L('Сначала новые','Newest first')}</option><option value="title" ${p.get('sort')==='title'?'selected':''}>${L('По названию','By title')}</option></select>`:''}</div>`;
 const articles=data.notes.filter(n=>n.kind==='article');const match=s=>s.toLowerCase().includes(q.toLowerCase());let html='';
 if(view==='overview')html=`<div class="overview-band">${[[articles.length,L('статей','articles')],[tools.length,L('инструментов','tools')],[data.materials.length,'PDF']].map(([n,s])=>`<div class="stat"><strong>${n}</strong><span>${s}</span></div>`).join('')}</div>${heading(L('Исследуйте направления','Explore a direction'))}<div class="topic-grid">${Object.entries(groups).map(([id,x])=>`<a class="topic-tile" href="${route('topic',{group:id})}" style="${visual({group:id}).style}"><span class="topic-icon visual-icon">${icon(visual({group:id}).shape)}</span><h3>${x[0]}</h3><p>${x[1]}</p><div class="topic-foot"><span>${articles.filter(n=>n.group===id).length} ${L('статей','articles')} · ${tools.filter(t=>t[4].includes(id)).length} ${L('инструм.','tools')}</span><b>→</b></div></a>`).join('')}</div>`;
 if(view==='library'){const list=articles.filter(n=>(domain==='all'||n.domain===domain)&&match(title(n)+' '+n.tags)).sort((a,b)=>p.get('sort')==='title'?title(a).localeCompare(title(b),lang):b.date.localeCompare(a.date));html=`<div class="article-grid">${list.map(card).join('')}</div>`;if(!list.length)html=''}
 if(view==='topic'){const list=articles.filter(n=>n.group===g);const ai=articles.filter(n=>(relatedAI[g]||[]).includes(n.id));html=`<a class="back-link" href="${route('overview')}">← ${L('Все направления','All directions')}</a>${heading(L('Статьи и практика','Articles & practice'))}<div class="article-grid">${list.map(card).join('')}</div>`;if(g!=='ai'&&ai.length)html+=heading(L('Связанные AI-практики','Related AI practices'))+`<div class="article-grid">${ai.map(card).join('')}</div>`;const ts=tools.filter(t=>t[4].includes(g));if(ts.length)html+=heading(L('Инструменты для этой темы','Tools for this topic'))+chips(ts);const ms=data.materials.filter(m=>materialGroup(m)===g);if(ms.length)html+=heading(L('Оригиналы PDF','Original PDFs'))+`<div class="resource-list">${ms.map(materialRow).join('')}</div>`}
 if(view==='tools'){const list=tools.filter(t=>match(t.slice(0,4).join(' ')));html=list.length?chips(list):''}
 if(view==='materials'){const list=data.materials.filter(m=>match(materialName(m)));html=list.length?`<div class="resource-list">${list.map(materialRow).join('')}</div>`:''}
 if(view==='sources'){const list=data.sources.filter(s=>match(s.title+' '+s.url+' '+s.notes.map(id=>title(data.notes.find(n=>n.id===id))).join(' ')));html=list.length?`<div class="resource-list">${list.map(s=>`<div class="resource"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a><small>${esc(new URL(s.url).hostname)}</small><div class="related-links">${s.notes.map(id=>data.notes.find(n=>n.id===id)).map(n=>n.kind==='tool'?`<button data-tool="${esc(tools.find(t=>t[5]===n.id)?.[0])}">${esc(title(n))}</button>`:`<a href="${esc(reader(n))}">${esc(title(n))} →</a>`).join('')}</div></div>`).join('')}</div>`:''}
 content.innerHTML=html||`<p class="empty">${L('Ничего не найдено. Попробуйте другой запрос.','No results. Try another search.')}</p>`;
 document.querySelector('#search')?.addEventListener('input',e=>{const pos=e.target.selectionStart;const url=new URL(location.href);url.searchParams.set('q',e.target.value);history.replaceState(null,'',url);render();const input=document.querySelector('#search');input.focus();try{input.setSelectionRange(pos,pos)}catch{}});
 document.querySelector('#sort')?.addEventListener('change',e=>{const url=new URL(location.href);url.searchParams.set('sort',e.target.value);history.pushState(null,'',url);render()});
}
const dialog=document.querySelector('#tool-dialog');document.querySelector('.dialog-close').ariaLabel=L('Закрыть','Close');document.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b){const t=tools.find(t=>t[0]===b.dataset.tool);if(!t)return;document.querySelector('#tool-detail').innerHTML=`<div class="tool-detail-icon">${toolBadge(t[0])}</div><h2 id="tool-title">${esc(t[0])}</h2><p>${esc(t[3])}</p><a class="primary-link" target="_blank" rel="noopener noreferrer" href="${esc(t[1])}">${L('Открыть инструмент','Open tool')} ↗</a>`;dialog.setAttribute('aria-labelledby','tool-title');dialog.showModal();return}const a=e.target.closest('a');if(a&&a.href.includes('reader.html')){try{sessionStorage.setItem('lab-return',location.pathname+location.search);sessionStorage.setItem('lab-scroll',String(scrollY))}catch{}}});
window.addEventListener('popstate',render);
try{const r=await fetch('./catalog.json');if(!r.ok)throw Error();data=await r.json();render();try{if(sessionStorage.getItem('lab-return')===location.pathname+location.search)window.scrollTo(0,Number(sessionStorage.getItem('lab-scroll'))||0)}catch{}}catch{content.textContent=L('Каталог не загрузился. Обновите страницу.','Could not load the catalog. Refresh the page.')}

document.addEventListener('error',e=>{if(e.target.matches?.('.tool-visual img'))e.target.remove()},true);
